### ISSUE TITLE
E_WARNING: parse_url() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by accell** [optimalisatie/above-the-fold-optimization#71] opened 2017-09-18 15:28 UTC
New Relic complains about this shortly after I enable the Javascript proxy and add an external script to the include list. Proxy CDN and Proxy URL are left to their defaults.

<img width="666" alt="stack_trace" src="https://user-images.githubusercontent.com/5078828/30550108-79dd7198-9c64-11e7-9b02-2bb17df83c6b.png">

**Comment by optimalisatie** [comment] 2017-09-18 16:05
Hi accell,

Thank you for reporting the issue!

Would it be possible for you to update `/wp-content/plugins/above-the-fold-optimization/includes/proxy.class.php` to test if an updated version solves the issue?

[proxy.class.php.txt](https://github.com/optimalisatie/above-the-fold-optimization/files/1311317/proxy.class.php.txt)

**Comment by accell** [comment] 2017-09-18 16:27
I've updated the file and the warnings seem to have disappeared.

**Comment by optimalisatie** [comment] 2017-09-18 17:26
Thank you for your help! The fix will be included in the next update.

The cause is related to the W3 Total Cache module. The original function was expecting a full URL and it received a relative URL.

The ABTF plugin originally was quickly setup for (custom) optimization projects, it was never intended as a public plugin. It essence it is still a quickly setup boiler plate based plugin. The quality has been improved by feedback and help from users.

Our engineers are currently focusing on more advanced optimization technologies. When the technologies are perfect and shaped into a good standard for long term usage, then it will be converted to a professionally developed, tested / reliable and easy to use plugin with documentation.

**Closed by optimalisatie** 2017-09-18 17:26 UTC
