### ISSUE TITLE
Scripts are breaking

### ISSUE THREAD

**Issue by Vidyut** [optimalisatie/above-the-fold-optimization#69] opened 2017-09-13 08:10 UTC
Some scripts are breaking due to dependencies. In this screenshot, it is a google map. It won't load. https://aamjanata.com/events/
![delete](https://user-images.githubusercontent.com/697822/30366540-01e13c4e-9889-11e7-9192-7ccd5ccd1e59.png)

**Comment by optimalisatie** [comment] 2017-09-17 20:35
Hi Vidyut,

Thank you for reporting the issue!

Regarding the missing dependency. It may not be the cause of the problem with the Google map. The script will load but the error indicates that the performance may not be optimal (the script has been waiting for an dependency that was never met). It appears that the dependency that was configured by WordPress is missing. It could be simply removed or merged with a different script.

Regarding Google maps. Google maps are more complex to optimize. There are solutions to enable async loading of Google maps but sometimes it requires customization of the (theme) javascript. Excluding of Google maps API related scripts is more difficult because Google maps API injects many independent scripts after the main script is loaded, which would be captured by the proxy.

If you want to load Google maps async you may find more information about the correct way to load the API in the following example:

https://developers.google.com/maps/documentation/javascript/examples/map-simple

When you initialize the map correctly when the API is loaded async then the map should load without an issue.

Excluding Google Maps API related scripts is possible as well. You will then need to manually discover the API related scripts for your specific website and add unique parts of the script URL’s to the exclude list.

For example, when many of the scripts contain the part /maps-api-v3/ you could simply add that string to the exclude list to match scripts that contain maps-api-v3, e.g. https://maps.googleapis.com/maps-api-v3/api/js/29/14/controls.js.

**Closed** 2017-09-20 19:32 UTC
