### ISSUE TITLE
Output Buffer Randomly Errored

### ISSUE THREAD

**Issue by noonanwebgroup** [optimalisatie/above-the-fold-optimization#14] opened 2017-01-20 03:15 UTC
Sometimes when I load a page (1/4 times, most often) on my website, running ABTF alongside W3 Total Cache, I will see a blank screen. I checked the error log and found this to be the problem:

```
PHP Catchable fatal error:  Object of class Abovethefold_OPP_W3TotalCache could not be converted to string in /plugins/w3-total-cache/Minify_MinifiedFileRequestHandler.php on line 914
[20-Jan-2017 03:11:48 UTC] PHP Fatal error:  Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0
```

**Comment by optimalisatie** [comment] 2017-01-20 18:29
Hi Noonanwebgroup,

Thank you for reporting the problem!

The error appears to have started since the last update of W3 Total Cache `v0.9.5.2`.

It appears to be a bug in W3 Total Cache that we cannot solve. W3 Total Cache offers a custom hook named `postprocessor` that isn't used in W3 Total Cache so it appears to be intended to enable extension by plugins such as ABTF. It may be a very old method that still exists in the current version of W3 Total Cache as a WordPress filter would be much better to add extensibility.

/plugins/w3-total-cache/lib/Minify/Minify.php line 604

```php
// do any post-processing (esp. for editing build URIs)
if (self::$_options['postprocessorRequire']) {
    require_once self::$_options['postprocessorRequire'];
}
if (self::$_options['postprocessor']) {
    $content = call_user_func(self::$_options['postprocessor'], $content, $type);
}
```

The error you discovered is caused by an attempt by W3 Total Cache to create a unique ID by flattening the option-configuration values that include the `postprocessor` hook. Since the hook is setup with a callable class for ABTF, the flattening fails.

We are unable to provide a quick fix for this issue. Our engineers will investigate it and try to find a solution for the next update that may become available in 2-3 weeks.

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by noonanwebgroup** [comment] 2017-01-20 18:57
Thank you for your reply. Is there anything that I could do to fix this short-term?

**Comment by optimalisatie** [comment] 2017-01-23 23:52
Hi Noonanwebgroup,

My apologies for the late reply, I missed you response.

I am sorry, as I said in my post, we are not able to provide a quick fix for the issue. It appears to be a bug in W3 Total Cache (it looks like that a very old extension method is available in W3 Total Cache that has been forgotten, and without it, extending W3 Total Cache is very difficult).

The problem has been added to our list and engineers will investigate the issue for the next update.

If we find a solution I will update this post.

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by noonanwebgroup** [comment] 2017-02-05 00:19
Has there been any update on this?

**Comment by optimalisatie** [comment] 2017-02-05 10:59
Hi!

It would be best to request support at W3 Total Cache and ask about the old fashion hook. If they forgot to remove it, you could ask them to replace it by a WordPress filter instead so that it will be possible to provide a stable plugin extension.

There is also a community initiative to improve W3 Total Cache that may be an option:

https://github.com/szepeviktor/w3-total-cache-fixed

Best Regards,
Jan Jaap
info@pagespeed.pro

**Closed** 2018-07-10 12:42 UTC
