### ISSUE TITLE
PHP Warning: Invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by Ost11** [optimalisatie/above-the-fold-optimization#18] opened 2017-02-05 18:11 UTC
Got these warnings in nginx's log: 
PHP Warning: Invalid argument supplied for foreach() in .../optimization.class.php on line 284.

WordPress v.4.7.2
ATF v.2.7.10

**Comment by Ost11** [comment] 2017-02-11 18:26
After enabling wp_debug, I get also this in nginx's error log:
"PHP Notice: Trying to get property of non-object in ..../optimization.class.php on line 284"

**Comment by optimalisatie** [comment] 2017-02-12 10:10
Hi Ost11,

Thank you for reporting the problem!

It is a bug with a yet unknown cause. The error indicates that WordPress script dependencies are not defined. The issue is rare and does not occur in most WordPress installations..

Our engineers have the issue scheduled for investigation. The issue will be resolved in the next update.

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by michelsup** [comment] 2017-03-15 14:02
You can then count me with the rare cases. ;)

**Comment by Bertsi** [comment] 2017-05-20 11:03
I got the same issue. 
Can you already estimate the date for the new update?
Thx

**Closed** 2018-07-10 12:42 UTC
